// <auto-generated />
using System;
using DbWebApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DbWebApi.Migrations
{
    [DbContext(typeof(ItemsDBContext))]
    [Migration("20231211162922_DeleteManagarTable")]
    partial class DeleteManagarTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DbWebApi.Model.Employe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("patronymic");

                    b.HasKey("Id");

                    b.ToTable("employes", (string)null);
                });

            modelBuilder.Entity("DbWebApi.Model.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTrip")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Docs")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EmployesId")
                        .HasColumnType("integer")
                        .HasColumnName("Employes_id");

                    b.Property<string>("LoadCrm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReadySort")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EmployesId");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("DbWebApi.Model.Trip", b =>
                {
                    b.HasOne("DbWebApi.Model.Employe", "Employes")
                        .WithMany("Trips")
                        .HasForeignKey("EmployesId")
                        .HasConstraintName("trips_employes_id_fkey");

                    b.Navigation("Employes");
                });

            modelBuilder.Entity("DbWebApi.Model.Employe", b =>
                {
                    b.Navigation("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
